[package]
name = "asciif"
version = "0.1.0"
authors = ["teemal <taymal1987@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.0"